# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Not_Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_rating', models.IntegerField(blank=True, choices=[(1, 'WORSE'), (2, 'BAD'), (3, 'AVERAGE'), (4, 'GOOD'), (5, 'EXCELLENT')], max_length=2)),
            ],
        ),
    ]
